--INIT STUDY GROUPS TABLE

INSERT INTO STUDY_GROUP (GROUP_NAME, PEOPLE_COUNT, COURSE_NUMBER) VALUES
('k-255', '20', '2');
INSERT INTO STUDY_GROUP (GROUP_NAME, PEOPLE_COUNT, COURSE_NUMBER) VALUES
('f-324', '20', '3');

--INIT CALENDAR TABLE something like that
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-01', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-02', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-03', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-04', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-05', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-06', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-07', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-08', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-09', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-10', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-11', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-12', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-13', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-14', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-15', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-16', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-17', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-18', NULL);
INSERT INTO CALENDAR (DATE, STUDY_GROUP_ID) VALUES
('2022-01-19', NULL);


--INIT PERSON TABLE

INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Vasiliy', 'Berezutskiy', 1);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Sergey', 'Rishikov', 2);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Anna', 'Ahmatova', 1);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Evgeniya', 'Zaytceva', 2);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Franchesko', 'Totti', 1);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Vasiliy', 'Lomovoy', 1);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Sergey', 'Ignashevich', 2);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Olga', 'Metlinskaya', 1);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Elena', 'Prekrasnaya', 2);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Maksimilliano', 'Bonucchi', 1);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Alex', 'Shepard', 2);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Roman', 'Pavlyuchenko', 1);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Muhammed', 'Sallah', 2);
INSERT INTO PERSON (FIRST_NAME, LAST_NAME, STUDY_GROUP_ID) VALUES
('Jordan', 'Larsson', 2);


-- --INIT PERSON2GROUP TABLE
-- INSERT INTO PERSON2GROUP (PERSON_ID, STUDY_GROUP_ID) VALUES
-- (1, 1);
-- INSERT INTO PERSON2GROUP (PERSON_ID, STUDY_GROUP_ID) VALUES
-- (2, 2);
-- INSERT INTO PERSON2GROUP (PERSON_ID, STUDY_GROUP_ID) VALUES
-- (3, 3);
-- INSERT INTO PERSON2GROUP (PERSON_ID, STUDY_GROUP_ID) VALUES
-- (4, 4);
-- INSERT INTO PERSON2GROUP (PERSON_ID, STUDY_GROUP_ID) VALUES
-- (5, 5);
-- INSERT INTO PERSON2GROUP (PERSON_ID, STUDY_GROUP_ID) VALUES
-- (6, 6);
-- INSERT INTO PERSON2GROUP (PERSON_ID, STUDY_GROUP_ID) VALUES
-- (7, 7);
-- INSERT INTO PERSON2GROUP (PERSON_ID, STUDY_GROUP_ID) VALUES
-- (8, 8);
-- INSERT INTO PERSON2GROUP (PERSON_ID, STUDY_GROUP_ID) VALUES
-- (9, 9);
-- INSERT INTO PERSON2GROUP (PERSON_ID, STUDY_GROUP_ID) VALUES
-- (10, 10);
-- INSERT INTO PERSON2GROUP (PERSON_ID, STUDY_GROUP_ID) VALUES
-- (11, 11);
-- INSERT INTO PERSON2GROUP (PERSON_ID, STUDY_GROUP_ID) VALUES
-- (12, 12);