DROP TABLE IF EXISTS STUDY_GROUP;

CREATE TABLE STUDY_GROUP (
                             ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                             GROUP_NAME VARCHAR(250) NOT NULL,
                             PEOPLE_COUNT INT,
                             COURSE_NUMBER INT
);

DROP TABLE IF EXISTS CALENDAR;

CREATE TABLE CALENDAR (
                          ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                          DATE VARCHAR(250) NOT NULL,
                          STUDY_GROUP_ID INTEGER,
                          CONSTRAINT FK_CALENDAR_GROUP FOREIGN KEY (STUDY_GROUP_ID) REFERENCES STUDY_GROUP(ID)
);

DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
                        ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
                        FIRST_NAME VARCHAR(250) NOT NULL,
                        LAST_NAME VARCHAR(250) NOT NULL,
                        STUDY_GROUP_ID INTEGER,
                        CONSTRAINT FK_PERSON_GROUP FOREIGN KEY (STUDY_GROUP_ID) REFERENCES STUDY_GROUP(ID)
);

-- DROP TABLE IF EXISTS PERSON2GROUP;
--
-- CREATE TABLE PERSON2GROUP (
--                               ID INT NOT NULL AUTOINCREMENT PRIMARY KEY,
--                               CONSTRAINT FK_ID_PERSON FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
--                                   CONSTRAINT FK_PERSON_GROUP FOREIGN KEY (STUDY_GROUP_ID) REFERENCES STUDY_GROUP(ID)
-- );
